apiVersion: apps/v1
kind: Deployment
metadata:
  name: nike-landing
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nike-landing
  template:
    metadata:
      labels:
        app: nike-landing
    spec:
      containers:
      - name: nike-landing
        image: docker.io/singhdocker2110/nike-landing-page:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nike-landing-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nike-landing
  ports:
  - port: 80
    targetPort: 80